site_name: Projektdokumentation
dev_addr: '127.0.0.1:80'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  
theme:
  name: material
  language: de
  font: false
  favicon: favicon.png
  logo: favicon.png

site_authors: "Toni Drechsel, Christoph Vogel, Stefan Keulig, Alex Neumann"

extra_css:
    - css/extra.css
    
nav:
  - Startseite: index.md
  - Phase 1: phase_1.md
  - Phase 2: phase_2.md
  - Phase 3: phase_3.md
  - Phase 4: phase_4.md
  - Phase 5: phase_5.md
  - Phase 6: phase_6.md
  - Phase 7: phase_7.md
  - Phase 8: phase_8.md
  - Phase 9: phase_9.md
  - Impressum: legal/imprint.md