site_name: Projektdokumentation
dev_addr: '0.0.0.0:80'

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  
theme:
  name: material
  language: de
  font: false
  favicon: favicon.png
  logo: favicon.png

site_author: "Stefan Keulig"

extra_css:
    - css/extra.css
    
nav:
  - Home: index.md
  - Getting Started: user-guide/getting-started.md
  - Impressum: legal/imprint.md
